m = float(input('Informe a quantidade de metros: '))
print('A quantidade de Quilômetros é {}'.format(m/1000))
print('A quantidade de centímetros é {}'.format(m*100))
print('A quantidade de Milímetros é {}'.format(m*1000))
print('A quantidade de Micrômetros é {}'.format(m/1000000))
print('A quantidade de Nanômetros é {}'.format(m/1000000000))
print('A quantidade de Angstrons é {}'.format(m/10000000000))